### ISSUE TITLE
[Windows] RetroArch crashes on load content

### ISSUE THREAD

**Issue by bslenul** [libretro/px68k-libretro#150]
Hey!

When having "d3d11" selected as video driver (I'm using Windows 10), the core crashes RetroArch entirely on load content.

**edit:** Doesn't seem to be related to D3D11, sometimes it also crashes with GL and Vulkan.

Compiled the core with DEBUG=1 and got that crash log, hopefully it'll help: [crash-211018-124241.log](https://github.com/libretro/px68k-libretro/files/7364165/crash-211018-124241.log)

**Comment by bslenul** [comment]
Hm, after updating to the latest core from the buildbot it doesn't work even with gl/glcore and vulkan either :/

Ran it with gdb:
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ff85f26972f in C68k_Exec (cpu=0x7ff85f75ade0 <C68K>, cycle=200)
    at m68000/c68k/c68kexec.c:205
205         NEXT
(gdb) bt full
#0  0x00007ff85f26972f in C68k_Exec (cpu=0x7ff85f75ade0 <C68K>, cycle=200)
    at m68000/c68k/c68kexec.c:205
        CPU = 0x7ff85f75ade0 <C68K>
        PC = 2094018528
        CCnt = 200
        Opcode = 4294967293
#1  0x00007ff85f25c783 in WinX68k_Exec () at libretro/winx68k.cpp:412
        m = 103
        n = 200
        clk_total = 162707
        clkdiv = 10
        usedclk = 392164128
        hsync = 0
        clk_next = 286
        clk_count = 0
        clk_line = 0
        KeyIntCnt = 0
        MouseIntCnt = 0
        t_start = 2682098187
        t_end = 32760
#2  0x00007ff85f25faec in exec_app_retro () at libretro/winx68k.cpp:829
        menu_key_down = 1607292736
        mbL = 0
        mbR = 0
        mouse_x = 32760
        mouse_y = 1607292736
        mouse_l = 32760
        mouse_r = 1597726667
        i = 32760
#3  0x00007ff85f33f087 in retro_run () at libretro.c:1421
        updated = false
#4  0x00007ff677b3ef8a in core_run () at retroarch.c:21298
        runloop_st = 0x7ff678b482e0 <runloop_state>
        current_core = 0x7ff678b48328 <runloop_state+72>
        core_poll_type_override = POLL_TYPE_OVERRIDE_DONTCARE
        new_poll_type = 2
        early_polling = false
        late_polling = true
        netplay_preframe = true
#5  0x00007ff677b3dbe7 in runloop_iterate () at retroarch.c:20617
        run_ahead_enabled = false
        run_ahead_secondary_instance = true
        want_runahead = false
        run_ahead_num_frames = 1
        run_ahead_hide_warnings = false
        i = 5
        dpad_mode = {ANALOG_DPAD_NONE, ANALOG_DPAD_NONE, ANALOG_DPAD_NONE,
          ANALOG_DPAD_NONE, ANALOG_DPAD_NONE, 521, 1838292064, 521,
          2084677984, 521, 3525003185, 32760, ANALOG_DPAD_NONE,
          ANALOG_DPAD_NONE, 1841168384, 521}
        p_rarch = 0x7ff678b26ce0 <rarch_st>
        input_st = 0x7ff678b6b5c0 <input_driver_st>
        audio_st = 0x7ff678b62740 <audio_driver_st>
        video_st = 0x7ff678b919c0 <video_driver_st>
        settings = 0x2096f2e9170
        runloop_st = 0x7ff678b482e0 <runloop_state>
        video_frame_delay = 0
        vrr_runloop_enable = false
        max_users = 5
        current_time = 323098371
        menu_pause_libretro = true
        core_paused = false
        slowmotion_ratio = 3
        cheevos_enable = false
        audio_sync = true
        discord_st = 0x7ff678b3cdf8 <rarch_st+90392>
#6  0x00007ff677b236fe in rarch_main (argc=1, argv=0x2096dbedb10, data=0x0)
    at retroarch.c:8987
        ret = 0
        app_exit = false
        p_rarch = 0x7ff678b26ce0 <rarch_st>
        runloop_st = 0x7ff678b482e0 <runloop_state>
        video_st = 0x7ff678b919c0 <video_driver_st>
#7  0x00007ff677d11ddd in SDL_main (argc=1, argv=0x2096dbedb10)
    at ui/drivers/ui_qt.cpp:4315
No locals.
#8  0x00007ff678265f5a in main_getcmdline ()
No symbol table info available.
#9  0x00007ff677b113c1 in __tmainCRTStartup ()
    at C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:321
        lock_free = <optimized out>
        fiberid = <optimized out>
        nested = <optimized out>
        lpszCommandLine = <optimized out>
        StartupInfo = {cb = 104, lpReserved = 0x2096d925860 "",
          lpDesktop = 0x2096d945d90 "Winsta0\\Default",
          lpTitle = 0x2096d943dc0 "G:\\msys64\\home\\B-S\\build\\retroarch_debug.exe", dwX = 0, dwY = 0, dwXSize = 0, dwYSize = 0, dwXCountChars = 0,
          dwYCountChars = 0, dwFillAttribute = 0, dwFlags = 0,
          wShowWindow = 0, cbReserved2 = 0, lpReserved2 = 0x0,
          hStdInput = 0xffffffffffffffff, hStdOutput = 0xffffffffffffffff,
          hStdError = 0xffffffffffffffff}
        inDoubleQuote = <optimized out>
#10 0x00007ff677b114d6 in WinMainCRTStartup ()
    at C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:176
        ret = 255
```
Looks pretty similar to this issue with PicoDrive core: https://github.com/libretro/picodrive/issues/184#issuecomment-946605356 🤔

**Comment by bslenul** [comment]
No idea if this helps or not, but the PicoDrive issue with ASLR is fixed with this: https://github.com/libretro/picodrive/commit/a704c216bacc5bd0ac3894fe72f8cf66839b6191 , on Discord devs were talking about "unsafe casts" but they also said it could be very hard to find :/

Also noticed while bisecting for another issue that it only crashes when launching content, it doesn't crash when using "Start Core" until you select the "RESET" option.

No idea if it helps but it seems related, there are A TON of warnings about "NEXT" (where it seems to crash) and "cast to pointer" during compilation: https://git.libretro.com/libretro/px68k-libretro/-/jobs/1119946/raw
e.g.:
```
m68000/c68k/c68kmac.inc:183:4: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  183 | ((*(u16*)PC) & 0xFF)
      |    ^
m68000/c68k/c68k_op0.inc:39:8: note: in expansion of macro 'FETCH_BYTE'
   39 |  src = FETCH_BYTE;
      |        ^~~~~~~~~~
m68000/c68k/c68kmac.inc:186:3: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  186 | (*(u16*)PC)
      |   ^
m68000/c68k/c68kmac.inc:59:14: note: in expansion of macro 'FETCH_WORD'
   59 |     Opcode = FETCH_WORD;        \
      |              ^~~~~~~~~~
m68000/c68k/c68kmac.inc:68:5: note: in expansion of macro 'NEXT'
   68 |     NEXT
      |     ^~~~
m68000/c68k/c68k_op0.inc:52:1: note: in expansion of macro 'RET'
   52 | RET(16)
      | ^~~
```

**Comment by riggles1** [comment]
Just wanted to chime in with, glad you're looking into this! Very appreciated.

The windows core is really important as it enables 55Hz sync (gsync/freesync/CRTEmudriver), really important for a smooth scrolling experience at the correct speeds.

**Comment by gouchi** [comment]
Hi,

The core should be available on buildbot now, otherwise you can get the build directly for [i686](https://git.libretro.com/libretro/px68k-libretro/-/jobs/2367013/artifacts/download) or [x86_64](https://git.libretro.com/libretro/px68k-libretro/-/jobs/2367012/artifacts/download).

If the issue is fixed after testing please close it.

Thank you.

**Comment by bslenul** [comment]
No more crashes on boot 👍
